# Generated by Django 5.1.3 on 2024-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
